<?php

/**
 * @file
 * Customize the service_links module.
 */

/**
 * Implementation hook_service_links_alter.
 */
function inno_service_links_service_links_alter(&$links) {
  if (isset($links['google_plus']) || isset($links['twitter']) || isset($links['linkedin']) || isset($links['facebook'])) {
    $links['google_plus']['icon'] =  base_path() . 'sites/all/themes/md_leaders/img/google_icon.png';
    $links['twitter']['icon'] =  base_path() . 'sites/all/themes/md_leaders/img/twitter_icon.png';
    $links['linkedin']['icon'] =  base_path() . 'sites/all/themes/md_leaders/img/linkedin_icon.png';
    $links['facebook']['icon'] =  base_path() . 'sites/all/themes/md_leaders/img/facebook_icon.png';
  }
}
