<?php

/**
 * hook_block_info implementation.
 */
function inno_mobile_slider_block_info() {
  $blocks['mobile_banner'] = array(
    'info' => t('Mobile Banner')
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function inno_mobile_slider_block_view($delta = '') {
  $block = array();


  switch ($delta) {
    case 'mobile_banner':
      $block['content'] = inno_mobile_banner_content();
      break;
  }


  return $block;
}


function inno_mobile_banner_content() {
  drupal_add_js(drupal_get_path('module', 'inno_mobile_slider') . '/jssor.slider.mini.js');
  drupal_add_js(drupal_get_path('module', 'inno_mobile_slider') . '/inno_mobile_slider.js');
  $image1 = drupal_get_path('module', 'inno_mobile_slider') . '/banner.jpg';
  //$image2 = drupal_get_path('module', 'inno_mobile_slider') . '/image2.jpg';
  $output = '<div id="slider1_container" style="position: relative; top: 0px; left: 0px; width: 600px; height: 300px;">
    <!-- Slides Container -->
    <div u="slides" style="cursor: move; position: absolute; overflow: hidden; left: 0px; top: 0px; width: 600px; height: 300px;">
        <div><a href="http://bit.ly/YouAreTheKeyBanner"><img u="image" src="' . $image1 . '" /></a></div>
    </div>
</div>';
  return $output;
}


/**
 * Implements hook_form_alter().
 */
function inno_mobile_slider_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "webform_client_form_205") {
    $form['#prefix'] = "<div class='feedback-button'>Feedback</div>";
    $form['#attributes'] = array('class' => array('feedback-webform'));
    $curr_path =  current_path() ;
    $form['curr_path'] = array(
      '#type' => 'hidden',
      '#value' => $curr_path
      );
    $form['#submit'][] = 'feedback_form_redirect';
  }
}


function feedback_form_redirect($form, $form_state) {
  drupal_set_message("Thank You for your valuable feedback.");
  $redirect_path = $form_state['input']['curr_path'];
  drupal_goto($redirect_path);
}
